WEBLOCAL = r'D:\aozorabunko@2016.12.29'
WEBURL   = r'http://vultr6.xisang.top'
CSV_PATH = WEBURL + '/index_pages/list_person_all_extended_utf8.zip'
EPUBPATH = r'D:\python\AozoraMobi-Storage\file\epub'
MOBIPATH = r'D:\python\AozoraMobi-Storage\file\mobi'
